imports:
    - { resource: tables.yml }

services:
    dmzx.mchat.admin.controller:
        class: dmzx\mchat\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@dbal.conn'
            - '@cache'
            - '@request'
            - '%dmzx.mchat.table.mchat%'
            - '%core.root_path%'
            - '%core.php_ext%'
    dmzx.mchat.main.controller:
        class: dmzx\mchat\controller\main_controller
        arguments:
            - '@dmzx.mchat.core'
            - '@request'
    dmzx.mchat.core:
        class: dmzx\mchat\core\mchat
        arguments:
            - '@dmzx.mchat.functions_mchat'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@auth'
            - '@pagination'
            - '@request'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
    dmzx.mchat.functions_mchat:
        class: dmzx\mchat\core\functions_mchat
        arguments:
            - '@config'
            - '@user'
            - '@auth'
            - '@log'
            - '@dbal.conn'
            - '@cache.driver'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.mchat.table.mchat%'
            - '%dmzx.mchat.table.mchat_sessions%'
    dmzx.mchat.listener:
        class: dmzx\mchat\event\listener
        arguments:
            - '@dmzx.mchat.functions_mchat'
            - '@dmzx.mchat.core'
            - '@controller.helper'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
