imports:
    - { resource: tables.yml }

services:
    dmzx.mchat.admin.controller:
        class: dmzx\mchat\controller\admin_controller
        arguments:
            - @dmzx.mchat.functions_mchat
            - @config
            - @controller.helper
            - @template
            - @log
            - @user
            - @service_container
            - @auth
            - @dbal.conn
            - @cache
            - @request
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - %dmzx.mchat.table.mchat_config%
    dmzx.mchat.controller:
        class: dmzx\mchat\controller\mchat
        arguments:
            - @dmzx.mchat.render_helper
            - @controller.helper
            - @request
    dmzx.mchat.render_helper:
        class: dmzx\mchat\core\render_helper
        arguments:
            - @dmzx.mchat.functions_mchat
            - @config
            - @controller.helper
            - @template
            - @log
            - @user
            - @auth
            - @dbal.conn
            - @cache
            - @pagination
            - @request
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - %dmzx.mchat.table.mchat%
    dmzx.mchat.functions_mchat:
        class: dmzx\mchat\core\functions_mchat
        arguments:
            - @template
            - @user
            - @auth
            - @log
            - @dbal.conn
            - @cache
            - %core.table_prefix%
            - %dmzx.mchat.table.mchat%
            - %dmzx.mchat.table.mchat_config%
            - %dmzx.mchat.table.mchat_sessions%
    dmzx.mchat.listener:
        class: dmzx\mchat\event\listener
        arguments:
            - @dmzx.mchat.render_helper
            - @auth
            - @config
            - @controller.helper
            - @template
            - @user
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - %dmzx.mchat.table.mchat%
        tags:
            - { name: event.listener }